
fortunerate: 0.2
diamondoredroprate: 0.0001
emeraldoredroprate: 0.0001
redstoneoredroprate: 0.0001
lapisoredroprate: 0.0001
glowstonedroprate: 0.0001
netherquartzoredroprate: 0.0001
claydroprate: 0.0001
turtleeggdroprate: 0.0001
glassdroprate: 0.0001

