
fortunerate: 0.2
diamondoredroprate: 0.0001
emeraldoredroprate: 0.0001
redstoneoredroprate: 0.0001
lapisoredroprate: 0.0001
glowstonedroprate: 0.0001
netherquartzoredroprate: 0.0001
claydroprate: 0.0001
turtleeggdroprate: 0.0001
glassdroprate: 0.0001
coaloredroprate: 0.0001
sealanterndroprate: 0.0001
icedroprate: 0.0001

addenchants: true
addeffects: true
addlore: true

disableplacement: true

broadcast: true
broadcastrange: 25

fixdroppedtrophies: true

ironoredroprate: 0.0001
goldoredroprate: 0.0001
copperoredroprate: 0.0001
amethystclusterdroprate: 0.0001

