name: MiningTrophies
main: com.github.crashdemons.miningtrophies.MiningTrophies
version: ${project.version}
author: crashdemons
api-version: 1.20
description: Drops rare trophies from mining
website: https://github.com/crashdemons




commands:
    MiningTrophies:
        usage: "/<command> <reload|give> [ore_block amount [targetuuser]]"
        description: Spawn a miningtrophie or edit miningtrophies config
        aliases: [mt,miningtrophy]
        permission: miningtrophies.command
permissions:
    miningtrophies.*:
        description: Gives all MiningTrophies permissions
        default: false
        children:
            miningtrophies.command: true
            miningtrophies.config.*: true
            miningtrophies.give: true
            miningtrophies.give.other: true
            miningtrophies.canberewarded: true
            miningtrophies.alwaysrewarded: true
    miningtrophies.config.*:
        description: Allows user to edit, save, or reload configs
        default: op
        children:
            miningtrophies.config.reload: true
    miningtrophies.command:
        description: Allows access to the miningtrophies command at all
        default: op
    miningtrophies.config.reload:
        description: Allows user to reload configs
        default: op
    miningtrophies.give:
        description: permission to get trophies with a command
        default: op
    miningtrophies.give.other:
        description: permission to get trophies with a command
        default: op
    miningtrophies.canberewarded:
        description: User can be rewarded for mining with trophies
        default: true
    miningtrophies.alwaysrewarded:
        description: Ignore drop rate for trophies and drop 100% of the time
        default: false
